apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku-app
  template:
    metadata:
      labels:
        app: sudoku-app
    spec:
      containers:
        - name: sudoku-app
          image: sudoku-app:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9097
              hostPort: 9097
          envFrom:
            - configMapRef:
                name: sudoku-config
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 256Mi
